### ISSUE TITLE
Won't work on IPAD/Android Chrome

### ISSUE THREAD

**Issue by dotnetwise** [cubiq/infiniwall#2]
Unless I have added this:

``` css
* {
     -webkit-overflow-scrolling: touch;
}
```
